from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company or currency pair that we are interested in trading"]
    instrument: Annotated[str, "Currency pair (e.g., EURUSD) for forex trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # Phase 1: research step
    market_report: Annotated[str, "Report from the Market Analyst (technical analysis)"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst (trader sentiment)"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    macro_report: Annotated[str, "Report from the Macro Analyst (macroeconomic analysis)"]

    # Phase 2: researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not (Bull vs Bear)"
    ]
    investment_plan: Annotated[str, "Plan generated by the Research Manager"]

    # Phase 3: Trader decision step
    trader_decision: Annotated[str, "Detailed trading decision analysis from the Trader"]
    trading_signal: Annotated[str, "Trading signal: STRONG_BUY, BUY, HOLD, SELL, STRONG_SELL"]
    entry_level: Annotated[float, "Recommended entry price level"]
    stop_loss: Annotated[float, "Stop loss price level"]
    take_profit_1: Annotated[float, "First take profit level (50% position)"]
    take_profit_2: Annotated[float, "Second take profit level (remaining 50%)"]
    conviction_level: Annotated[int, "Confidence level 0-100%"]
    risk_reward_ratio: Annotated[float, "Risk to reward ratio"]
    position_size: Annotated[str, "Recommended position size"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader (legacy field)"]

    # Phase 4: risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
