from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company or currency pair that we are interested in trading"]
    instrument: Annotated[str, "Currency pair (e.g., EURUSD) for forex trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # Phase 1: research step
    market_report: Annotated[str, "Report from the Market Analyst (technical analysis)"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst (trader sentiment)"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    macro_report: Annotated[str, "Report from the Macro Analyst (macroeconomic analysis)"]

    # Phase 2: researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not (Bull vs Bear)"
    ]
    investment_plan: Annotated[str, "Plan generated by the Research Manager"]

    # Phase 3: Trader decision step
    trader_decision: Annotated[str, "Detailed trading decision analysis from the Trader"]
    trading_signal: Annotated[str, "Trading signal: STRONG_BUY, BUY, HOLD, SELL, STRONG_SELL"]
    entry_level: Annotated[float, "Recommended entry price level"]
    stop_loss: Annotated[float, "Stop loss price level"]
    take_profit_1: Annotated[float, "First take profit level (50% position)"]
    take_profit_2: Annotated[float, "Second take profit level (remaining 50%)"]
    conviction_level: Annotated[int, "Confidence level 0-100%"]
    risk_reward_ratio: Annotated[float, "Risk to reward ratio"]
    position_size: Annotated[str, "Recommended position size"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader (legacy field)"]

    # Phase 4: risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    final_risk_decision: Annotated[str, "Comprehensive risk analysis and final decision from Risk Manager"]
    risk_adjusted_signal: Annotated[str, "Risk-adjusted trading signal from Phase 4"]
    final_entry: Annotated[float, "Final entry price approved by Risk Manager"]
    final_stop_loss: Annotated[float, "Final stop loss adjusted by Risk Manager"]
    final_position_size: Annotated[str, "Final position size adjusted by Risk Manager"]
    adjustment_reason: Annotated[str, "Reason for any adjustments made in Phase 4"]
    risk_approval_status: Annotated[str, "APPROVED, APPROVED_WITH_ADJUSTMENTS, or REJECTED"]

    # Phase 5: Execution and monitoring step
    execution_status: Annotated[str, "EXECUTED, REJECTED, INVALID, PENDING"]
    execution_timestamp: Annotated[str, "When the order was executed"]
    order_id: Annotated[str, "Unique order identifier"]
    order_details: Annotated[dict, "Order execution details: entry_price, fill_price, quantity, slippage"]
    position_id: Annotated[str, "Unique position identifier for tracking"]
    position_tracking: Annotated[dict, "Real-time position data: entry, stop_loss, tp1, tp2, current, pnl"]
    
    # Monitoring fields
    unrealized_pnl_pips: Annotated[float, "Unrealized P&L in pips"]
    unrealized_pnl_usd: Annotated[float, "Unrealized P&L in USD"]
    realized_pnl_pips: Annotated[float, "Realized P&L in pips"]
    realized_pnl_usd: Annotated[float, "Realized P&L in USD"]
    execution_slippage: Annotated[float, "Slippage in pips between expected and actual fill"]
    execution_quality: Annotated[float, "Execution quality score 0-100 (higher is better)"]
    
    # Trade logging
    trade_logged: Annotated[bool, "Whether trade was logged to journal"]
    trade_id: Annotated[str, "Trade journal identifier"]
    
    # Portfolio metrics
    portfolio_stats: Annotated[dict, "Portfolio statistics: margin used, unrealized PnL, equity"]
    
    # Invalidation signals
    invalidation_reason: Annotated[str, "Reason position was invalidated/closed"]
    market_conditions: Annotated[dict, "Current market conditions: volatility, spread, sessions"]
    
    # Current price tracking
    current_price: Annotated[float, "Current market price for position monitoring"]
    price_history: Annotated[list, "Recent price history for volatility calculation"]
